### ISSUE TITLE
Missing file: CMakeLists.txt

### ISSUE THREAD

**Issue by pulimento** [sokunmin/android_webrtc_tensorflowlite#1]
The file `CMakeLists.txt` is needed in order to make a build. It's referenced [here](https://github.com/sokunmin/android_webrtc_tensorflowlite/blob/master/app/build.gradle#L46)

Would you be so kind to upload the file? Thanks

**Comment by sokunmin** [comment]
I've committed the missing file. Please update your project. CMakeLists.txt is not used in this example. You can do some modifications and compile with native code if you'd like to do something different.
Check out TensorFlow's github. https://github.com/tensorflow/tensorflow/tree/f53c5dad3f37fa9e1503dccadb8714a089f3df87/tensorflow/examples/android/jni

**Comment by pulimento** [comment]
Thanks for the fast response, will try again soon

**Comment by pulimento** [comment]
All is working perfectly. Thanks!
